jobs:

- job: OSX
  pool:
    vmImage: 'macOS 10.13'

  variables:
    os_name: OSX

  strategy:
    matrix:
      node_10_x:
        node_version: 10.x

  steps:
  - template: .azure-pipelines-steps.yml
